name: roslib
description: Interface with a ROS node over websockets with rosbridge, heavily influenced by roslibjs and follows the same structure.
version: 0.0.3
author: Conrad Heidebrecht <conrad.heidebrecht@gmail.com>
homepage: https://github.com/eternali/roslib

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  web_socket_channel: ^1.0.12

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
